map = {
'30824':'Indicadores de renta media',
'30825':'Distribución por fuente de ingresos',
'30826':'Distribución de la renta por unidad de consumo',
'30827':['Distribución de la renta por unidad de consumo','Sexo','Tramos de edad'],
'30828':['Distribución de la renta por unidad de consumo','Sexo','Nacionalidad'],
'30829':['Distribución de la renta por unidad de consumo','Sexo'],
'30830':['Distribución de la renta por unidad de consumo','Sexo','Tramos de edad'],
'30831':['Distribución de la renta por unidad de consumo','Sexo','Nacionalidad'],
'30832':'Indicadores demográficos',
'37677':'Indicadores de renta media'}

variables = ['Renta neta media por persona ', 'Renta neta media por hogar',
'Media de la renta por unidad de consumo',
'Mediana de la renta por unidad de consumo',
'Renta bruta media por persona', 'Renta bruta media por hogar',
'Fuente de ingreso: salario', 'Fuente de ingreso: pensiones',
'Fuente de ingreso: prestaciones por desempleo',
'Fuente de ingreso: otras prestaciones',
'Fuente de ingreso: otros ingresos',
'Edad media de la población',
'Porcentaje de población menor de 18 años',
'Porcentaje de población de 65 y más años',
'Tamaño medio del hogar',
'Porcentaje de hogares unipersonales',
'Población',
'Porcentaje de población española',
'Índice de Gini',
'Distribución de la renta P80/P20']