amm_network: 
  provider: 3
  table: road_segments
  codes: ['999']
  kinds: ['VIA']

osm:
  provider: 2
  table: pois
  description: >
    Open Street Map takes query dictionaries in the form that OSMPythonTools establish. Areas can be called by name. We use municipalities here, but make sure the names are accessed by Nominatim
  categories: {
    'park':{'elementType':['way','relation'],'selector':'"leisure"="park"','color':'green'},
    'square':{'elementType':['way','relation'],'selector':'"place"="square"','color':'black'},
    'pedestrian':{'elementType':['way','relation'],'selector':'"highway"="pedestrian"','color':'black'},
    'forest':{'elementType':['way','relation'],'selector':'"landuse"="forest"','color':'green'},
    'bus-stop':{'elementType':'node','selector':'"highway"="bus_stop"','color':'red'},
    'subway-stop': {'elementType':'node','selector':'"railway"="subway_entrance"','color':'red'}
    }
  areas: ['Alcalá de Henares']

catastro:
  provider: 1
  table: pois
  description: >
    Takes only Province-Municipality codes. 
  codes: ['28005']

ine_adrh:
  provider: 3
  table: boundary_data
  description: 
  codes: ['28005']
  years: ['2018']

ine_geo:
  provider: 4
  table: boundary_geo
  description:
  years: ['2018']

edm2018:
  provider: 5
  table: trip_data
  codes: ['005']


